
package org.nema.dicom.wg23;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HostService", targetNamespace = "http://wg23.dicom.nema.org/")
public class HostService
    extends Service
{

    private final static URL HOSTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;        
        HOSTSERVICE_WSDL_LOCATION = url;
    }

    public HostService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HostService() {
        super(HOSTSERVICE_WSDL_LOCATION, new QName("http://wg23.dicom.nema.org/", "HostService"));
    }

    /**
     * 
     * @return
     *     returns Host
     */
    @WebEndpoint(name = "HostPort")
    public Host getHostPort() {
        return (Host)super.getPort(new QName("http://wg23.dicom.nema.org/", "HostPort"), Host.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Host
     */
    @WebEndpoint(name = "HostPort")
    public Host getHostPort(WebServiceFeature... features) {
        return (Host)super.getPort(new QName("http://wg23.dicom.nema.org/", "HostPort"), Host.class, features);
    }

}
